# Python CircleCI 2.1 configuration file
version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build:
    executor: 
      name: python/default
      tag: "3.12"

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install pytest pytest-cov
            pip install .
      # Step 3: run tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -v --cov=ncjson --cov-report=html
